### ISSUE TITLE
Cannot create operator of type 'MSRAFill' on the device 'CUDA'

### ISSUE THREAD

**Issue by XiongChengxin** [facebookresearch/VMZ#42]
I noticed there are two similiar issues, but the difference is I have GPU. I install my caffe2 referring to https://github.com/facebookresearch/R2Plus1D/blob/master/tutorials/Installation_guide.md , my error message is as follows.

Traceback (most recent call last):
  File "/data/xiongcx/R2Plus1D/R2Plus1D-master/tools/train_net.py", line 509, in <module>
    main()
  File "/data/xiongcx/R2Plus1D/R2Plus1D-master/tools/train_net.py", line 504, in main
    Train(args)
  File "/data/xiongcx/R2Plus1D/R2Plus1D-master/tools/train_net.py", line 344, in Train
    workspace.RunNetOnce(test_model.param_init_net)
  File "/home/xiongcx/pytorch/build/caffe2/python/workspace.py", line 201, in RunNetOnce
    StringifyProto(net),
  File "/home/xiongcx/pytorch/build/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at operator.cc:212] op. Cannot create operator of type 'MSRAFill' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: output: "gpu_0/conv1_middle_w" name: "" type: "MSRAFill" arg { name: "shape" ints: 45 ints: 3 ints: 1 ints: 7 ints: 7 } device_option { device_type: 1 cuda_gpu_id: 0 }

Do you have any ideas?

**Comment by dutran** [comment]
More likely you don't have CUDA driver installed on your machine.
