### ISSUE TITLE
something wrong using caffe2 installed with anaconda

### ISSUE THREAD

**Issue by liqima** [facebookresearch/VMZ#70]
Hi, I installed caffe2 with anaconda, and something wrong when I run tools/extract_features.py
`Traceback (most recent call last):
  File "extract_features.py", line 334, in <module>
    main()
  File "extract_features.py", line 329, in main
    ExtractFeatures(args)
  File "extract_features.py", line 134, in ExtractFeatures
    devices=gpus,
  File "/home/maliqi/anaconda2/envs/detect/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 34, in Parallelize_GPU
    Parallelize(*args, **kwargs)
  File "/home/maliqi/anaconda2/envs/detect/lib/python2.7/site-packages/caffe2/python/data_parallel_model.py", line 231, in Parallelize
    input_builder_fun(model_helper_obj)
  File "extract_features.py", line 109, in input_fn
    use_local_file=args.use_local_file,
  File "/home/maliqi/video_repetition/utils/model_helper.py", line 127, in AddVideoInput
    data, label = model.net.VideoInput(
  File "/home/maliqi/anaconda2/envs/detect/lib/python2.7/site-packages/caffe2/python/core.py", line 2179, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method VideoInput is not a registered operator. Did you mean: []`

I find some discuss [here](https://github.com/facebookresearch/VMZ/issues/44) and [here](https://github.com/facebookresearch/VMZ/issues/2), sound like I have to use caffe2 installed from source. But unfortunatly, my machine cannot do that (I know how to compile install caffe2, here I just can't do that), so, I want to ask is there another way to solve this problem?
thanks.

**Comment by shenqiang-Yuan** [comment]
hi, i have encountered with the same problem, seems you should install caffe2 from source compile with opencv and ffmpeg installed, while switch on USE_OPENCV,FFMPEG,and LMDB,with command like this: cd pytorch && USE_OPENCV=1 USE_FFMPEG=1 USE_LMDB=1 sudo python setup.py install

**Comment by isamabdullah88** [comment]
You just not need to build from source, you need to build from source with ffmpeg and opencv. Maybe, you can ask for a precompiled caffe2 from someone who has compiled it from source with ffmpeg and opencv.

**Comment by dutran** [comment]
Build from source with USE_FFMPEG and USE_OPENCV is ON should solve this.
